# spring
spring:
  # profiles
  profiles:
    active: local
# framework
framework:
  # swagger
  swagger:
    base-package: com.afrobank.afrobank.web.controller
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: warn
    com.afrobank.afrobank: info
# mybatis plus
mybatis-plus:
  type-aliases-package: com.afrobank.afrobank.entity,com.afrobank.afrobank.model.*
  mapper-locations: classpath:mappers/*Mapper.xml
